[package]
name = "fgg"
version = "0.1.0"
authors = ["Clay66"]
description = "A CLI application to connect to The Fighting Game Glossary"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
